spring :
  application.name : spring-batch-learning
  datasource :
    url : jdbc:h2:./db
    hikari.maximum-pool-size : 10
  h2.console.enabled : true
  batch :
    jdbc.initialize-schema : always # always, never, embedded
#    job.enabled : false
#    job.name : taskletJob
#    job.name : chunkJob
    job.name : chunkMultithreadedJob
#    job.name : chunkAsyncJob

#logging:
#  level:
#    com.zaxxer.hikari: debug